from django.urls import path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

from core.views import (
    ping,
    DeficitView,
    SurplusView,
    RevenueView,
    SalesFiltersView,
    SalesSummaryView,
    ForecastAccuracyView,
    ForecastDemandChartView,
    ForecastSummaryView,
    ForecastByProductsView,
    SalesChartView,
    SalesRevenueChartView,
    SalesByShopsView,
    SalesByProductsView,
    CriticalStockView,
    ProblemProductsView,
    SuppliesFiltersView,
    SuppliesSummaryView,
    SuppliesScheduledView,
    SuppliesInTransitView,
    SuppliesTableView,
    SuppliesDispatchView,
    PickingFiltersView,
    PickingSummaryView,
    PickingTodayView,
    PickingDetailView,
    PickingItemPatchView,
    PickingSaveView,
    PickingDispatchView,
    ReportsView,
    LoginView,
    RefreshView,
    MeView,
)

urlpatterns = [
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/refresh/", RefreshView.as_view(), name="auth-refresh"),
    path("auth/me/", MeView.as_view(), name="auth-me"),
    path("ping/", ping),
    path("sales/filters/", SalesFiltersView.as_view()),
    path("sales/summary/", SalesSummaryView.as_view()),
    path("sales/by-shops/", SalesByShopsView.as_view()),
    path("sales/by-products/", SalesByProductsView.as_view()),
    path("dashboard/deficit/", DeficitView.as_view()),
    path("dashboard/surplus/", SurplusView.as_view()),
    path("dashboard/revenue/", RevenueView.as_view()),
    path("dashboard/forecast-accuracy/", ForecastAccuracyView.as_view()),
    path("forecast/demand-chart/", ForecastDemandChartView.as_view()),
    path("forecast/summary/", ForecastSummaryView.as_view()),
    path("forecast/by-products/", ForecastByProductsView.as_view()),
    path("dashboard/sales-chart/", SalesChartView.as_view()),
    path("sales/sales-chart/", SalesRevenueChartView.as_view()),
    path("dashboard/critical-stock/", CriticalStockView.as_view()),
    path("dashboard/problem-products/", ProblemProductsView.as_view()),
    path("supplies/filters/", SuppliesFiltersView.as_view()),
    path("supplies/summary/", SuppliesSummaryView.as_view()),
    path("supplies/scheduled/", SuppliesScheduledView.as_view()),
    path("supplies/in-transit/", SuppliesInTransitView.as_view()),
    path("supplies/dispatch/", SuppliesDispatchView.as_view()),
    path("supplies/", SuppliesTableView.as_view()),
    path("picking/filters/", PickingFiltersView.as_view()),
    path("picking/summary/", PickingSummaryView.as_view()),
    path("picking/today/", PickingTodayView.as_view()),
    path("picking/items/<uuid:item_id>/", PickingItemPatchView.as_view()),
    path("picking/<uuid:shop_id>/save/", PickingSaveView.as_view()),
    path("picking/<uuid:shop_id>/dispatch/", PickingDispatchView.as_view()),
    path("picking/<uuid:shop_id>/", PickingDetailView.as_view()),
    path("reports/<str:kind>/", ReportsView.as_view(), name="reports"),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]