# Generated by Django 6.0.3 on 2026-03-23 12:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_qty', models.IntegerField(default=0)),
                ('min_stock', models.IntegerField(default=0)),
                ('max_stock', models.IntegerField(default=0)),
                ('avg_daily_sales', models.FloatField(default=0.0)),
                ('safety_stock_days', models.IntegerField(default=3)),
                ('reorder_cycle_days', models.IntegerField(default=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='core.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='core.shop')),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остатки',
                'unique_together': {('product', 'shop')},
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shop')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('snapshot_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shop')),
            ],
            options={
                'verbose_name': 'Снимок остатка',
                'unique_together': {('product', 'shop', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='StockDeviation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deviation_type', models.CharField(choices=[('deficit', 'Недостаток'), ('surplus', 'Избыток')], max_length=20)),
                ('deviation_qty', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='core.inventory')),
            ],
            options={
                'verbose_name': 'Отклонение',
                'verbose_name_plural': 'Отклонения',
                'indexes': [models.Index(fields=['is_active', 'deviation_type'], name='core_stockd_is_acti_cf03f7_idx'), models.Index(fields=['calculated_at'], name='core_stockd_calcula_13f647_idx')],
            },
        ),
    ]
