# Generated by Django 6.0.3 on 2026-03-23 17:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorysnapshot',
            options={'verbose_name': 'Снимок остатка', 'verbose_name_plural': 'Снимки остатков'},
        ),
        migrations.CreateModel(
            name='ForecastEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('predicted_qty', models.IntegerField(help_text='Прогнозируемое количество продаж')),
                ('actual_qty', models.IntegerField(blank=True, help_text='Фактическое количество продаж', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='core.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='core.shop')),
            ],
            options={
                'verbose_name': 'Прогноз спроса',
                'verbose_name_plural': 'Прогнозы спроса',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='core_foreca_date_fd50f3_idx')],
                'unique_together': {('product', 'shop', 'date')},
            },
        ),
    ]
