# Generated by Django 6.0.3 on 2026-04-05 16:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_inventorysnapshot_options_forecastentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='price_at_sale',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Цена за единицу в момент продажи', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_count', models.IntegerField(default=0)),
                ('total_qty', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.shop')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sales',
            name='receipt',
            field=models.ForeignKey(blank=True, help_text='Чек, в котором была совершена продажа', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.receipt'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['product', 'shop', 'date'], name='core_sales_product_8cce5e_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['receipt'], name='core_sales_receipt_a7f0e2_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['shop', 'created_at'], name='core_receip_shop_id_14dd72_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['created_at'], name='core_receip_created_17a926_idx'),
        ),
    ]
