# Generated by Django 6.0.3 on 2026-04-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sales_price_at_sale_alter_sales_date_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchshipment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchshipment',
            name='planned_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchshipment',
            name='planned_dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchshipment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланирована'), ('in_transit', 'В пути'), ('delivered', 'Доставлена'), ('cancelled', 'Отменена')], default='delivered', max_length=20),
        ),
        migrations.AddIndex(
            model_name='batchshipment',
            index=models.Index(fields=['shop', 'status'], name='core_batchs_shop_id_c31f7f_idx'),
        ),
        migrations.AddIndex(
            model_name='batchshipment',
            index=models.Index(fields=['planned_dispatch_date'], name='core_batchs_planned_982dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='batchshipment',
            index=models.Index(fields=['status', 'planned_dispatch_date'], name='core_batchs_status_105a28_idx'),
        ),
    ]
