# Generated by Django 6.0.3 on 2026-04-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_batchshipment_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchshipment',
            name='picked_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
