# Generated by Django 6.0.5 on 2026-05-23 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("core", "UserProfile")

    for user in User.objects.all():
        if UserProfile.objects.filter(user_id=user.pk).exists():
            continue
        role = "admin" if user.is_superuser else "admin"
        UserProfile.objects.create(user_id=user.pk, role=role)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_batchshipment_picked_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('logist', 'Логист'), ('picker', 'Сборщик заказов')], default='picker', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.RunPython(create_profiles_for_existing_users, migrations.RunPython.noop),
    ]
