# Generated by Django 6.0.5 on 2026-06-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_create_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchshipment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланирована'), ('ready_to_ship', 'Готов к отправке'), ('in_transit', 'В пути'), ('delivered', 'Доставлена'), ('cancelled', 'Отменена')], default='delivered', max_length=20),
        ),
    ]
